### ISSUE TITLE
New rule: `Modifier` Should have default value

### ISSUE THREAD

**Issue by BraisGabin** [appKODE/detekt-rules-compose#4]
Enforce that `modifier` always have a default value
non compilant:
`modifier: Modifier`

compilant:
`modifier: Modifier = Modifier`
`modifier: Modifier = Modifier.padding(4.dp)`

**Comment by dimsuz** [comment]
I have also thought about adding a separate rule which would enforce putting optional parameters _after_ required parameters, (+not allowing to intersperse them). Looks like this makes sense specifically for composable functions (not generally) and follows Compose internal style: so that you can write e.g. `Text("Hello", TextStyle.H2)`. This would require named args if at least one optional parameter is present before required ones. Not yet sure how useful such rule would be, thought about trying it on our private codebases first.

**Comment by BraisGabin** [comment]
😂 I had on my TODO list "Open an issue to enforce required parameters first". I just crosslined it (Unless you want the issue to track this kind of things)

**Comment by dimsuz** [comment]
Hah, nice! No need then, it's on my TODO list also, will do soon.

**Comment by BraisGabin** [comment]
Sounds good!

**Comment by dimsuz** [comment]
I have actually made a two new rules:

- `ModifierDefaultValue` checks that default value (if present) is nothing other than `Modifier`, having a complex expressions there can lead to issues as I described in the [comment](https://github.com/appKODE/detekt-rules-compose/issues/4#issuecomment-1143440764) above
- `MissingModifierDefaultValue` which reports an error if modifier has no default value. Lint rules bundled with compose do not enforce modifier having a default value, so I thought that some folks might want to disable this rule.
